server:
  port: 8803

spring:
  application:
    name: cloud-stream-consumer
  rabbitmq:
    host: 192.168.59.151
    port: 5672
    username: admin
    password: 123
  cloud:
    stream:
      binders: # 在此处配置表示要绑定的rabbitmq的服务信息
        defaultRabbit: #表示定义的名称，用于与binding整合
          type: rabbit # 消息组件的类型
      bindings: # 服务的整合处理
        input: # 这个名称是通道的名称
          destination: studyExchange # 表示要使用的Exchange名称定义
          content-type: application/json # 设置消息类型，本次为json，文本则设置为：text/plain
          binder: defaultRabbit  #  设置要绑定的消息服务的具体类型
          group: qhy

eureka:
  client:
    register-with-eureka: true  #表示将自己注册进Eureka Server
    fetch-registry: true        #表示是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka   #集群版
  instance:
    lease-renewal-interval-in-seconds: 2 # 设置心跳的时间间隔(默认是30s)
    lease-expiration-duration-in-seconds: 5 # 如果现在超过了5s的间隔 (默认是90s)
    instance-id: receive-8803.com # 在信息列表时显示主机名称
    prefer-ip-address: true    # 访问的路径变为ip地址
