#服务端口号
server:
  port: 8001

#服务名称
spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource  #当前数据源的操作类型
    driver-class-name: org.gjt.mm.mysql.Driver    #mysql驱动包
    url: jdbc:mysql://localhost:3306/db2019?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: qhy

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.qhy.springcloud.entities  #entity所在包

#单机
eureka:
  client:
    register-with-eureka: true #是否向注册中心注册自己
    fetchRegistry: true #是否从注册中心抓取已有的注册信息 默认true，集群必须设置为true
    service-url:
      #      设置与eureka server交互的地址查询服务和注册服务都需要依赖这个地址
      defaultZone: http://localhost:7001/eureka #单机版
  instance:
    instance-id: payment8001
    prefer-ip-address: true #访问路径可以显示ip地址
    #Eureka客户端向服务端发送心跳的时间间隔，单位为秒（默认是30秒）
    lease-renewal-interval-in-seconds: 1
    #Eureka服务端在收到最后一次心跳后等待时间上限，单位为秒（默认为90秒），超市将剔除服务
    lease-expiration-duration-in-seconds: 2

#集群
#eureka:
#  client:
#    register-with-eureka: true #是否向注册中心注册自己
#    fetchRegistry: true #是否从注册中心抓取已有的注册信息 默认true，集群必须设置为true
#    service-url:
#      #      设置与eureka server交互的地址查询服务和注册服务都需要依赖这个地址
#     defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka #集群版
#  instance:
#    instance-id: payment8001
#    prefer-ip-address: true #访问路径可以显示ip地址
