server:
  port: 80

eureka:
  client:
    register-with-eureka: false #是否向注册中心注册自己
    service-url:
      #      设置与eureka server交互的地址查询服务和注册服务都需要依赖这个地址
      defaultZone: http://localhost:7001/eureka #单机版


feign:
  hystrix:
    enabled: true #如果处理自身的容错就开启。开启方式与生产端不一样。
